import type {
  SmartLockDevice,
  Alert,
  LocationHistoryEntry,
  ActivityEvent,
} from '@/types/smartlock';

function daysAgo(days: number, hours = 0, minutes = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(d.getHours() - hours, d.getMinutes() - minutes, 0, 0);
  return d.toISOString();
}

function hoursAgo(hours: number, minutes = 0): string {
  return daysAgo(0, hours, minutes);
}

function minutesAgo(minutes: number): string {
  return daysAgo(0, 0, minutes);
}

export const mockDevices: SmartLockDevice[] = [
  {
    deviceId: 'SL-001',
    deviceName: 'Front Gate Lock',
    status: 'online',
    lastSeen: minutesAgo(2),
    device: { imei: '356938035643809', modelId: 'SL-PRO-200', serialNumber: 'SN-FL-2024-001', appVersion: '2.4.1', sdkVersion: '1.8.3', hardwareVersion: 'HW3.2', bootReason: 'power_on', uptime: 345600 },
    power: { batteryVoltage: 4.15, batteryPercentage: 89, isCharging: false, isUsbConnected: false, isExternalPower: false, isLowBattery: false },
    cellular: { operator: 'T-Mobile', networkType: 'LTE-M', rssi: -72, signalQuality: 85, ip: '10.24.36.112' },
    gps: { isFixed: true, latitude: 39.7684, longitude: -86.1581, altitude: 218, speed: 0, heading: 0, satellites: 12, hdop: 1.2, accuracy: 4.5, lastFix: minutesAgo(1), lastLocation: 'Indianapolis, IN' },
    lock: { lockStatus: true, doorStatus: false, motorStatus: 'idle', motorCurrent: 0, positionSensor: true, lastLockTime: hoursAgo(2), lastUnlockTime: hoursAgo(3), unlockMethod: 'keypad', unlockCount: 142, failedUnlockCount: 2 },
    access: { keypad: { enabled: true, lastUsed: hoursAgo(2), count: 87 }, nfc: { enabled: true, lastUsed: hoursAgo(5), count: 31 }, bluetooth: { enabled: true, lastUsed: daysAgo(1), count: 18 }, remote: { enabled: true, lastUsed: hoursAgo(1), count: 6 } },
    tamper: { tamperStatus: false, caseOpen: false, wireCut: false, lockBreak: false, abnormalVibration: false, forcedUnlock: false, tamperCount: 0, lastTamperTime: '' },
    accelerometer: { motion: false, x: 0.02, y: -0.01, z: 9.81, harshBraking: false, harshAcceleration: false, sharpTurn: false, impactCount: 0, drivingScore: 95 },
    trip: { vehicleStatus: 'stationary', tripStatus: false, tripId: '', distance: 0, maximumSpeed: 0, overspeedCount: 0 },
    geofence: { status: 'inside', geofenceId: 'GF-INDY-001', violation: false, lastEvent: daysAgo(3) },
    sensors: { temperature: 72.5, internalTemperature: 85.2, humidity: 45, hardwareSensorStatus: true },
    security: { deviceBinding: true, vehicleId: 'VH-2024-001', customerId: 'CUST-1001', certificateStatus: true, secureBoot: true, firmwareSignature: true },
    memory: { totalStorage: 16384, usedStorage: 4096, freeStorage: 12288 },
    diagnostics: { lastDiagnosticTime: minutesAgo(30), errorCodes: [], systemHealth: 'good' },
    rtc: { rtcTime: minutesAgo(1), rtcSynced: true },
  },
  {
    deviceId: 'SL-002',
    deviceName: 'Warehouse Side Door',
    status: 'online',
    lastSeen: minutesAgo(5),
    device: { imei: '354892018475623', modelId: 'SL-STD-100', serialNumber: 'SN-WH-2024-002', appVersion: '2.3.8', sdkVersion: '1.7.9', hardwareVersion: 'HW3.0', bootReason: 'watchdog_reset', uptime: 86400 },
    power: { batteryVoltage: 3.89, batteryPercentage: 67, isCharging: false, isUsbConnected: false, isExternalPower: false, isLowBattery: false },
    cellular: { operator: 'AT&T', networkType: 'LTE-M', rssi: -85, signalQuality: 62, ip: '10.24.36.205' },
    gps: { isFixed: true, latitude: 39.7321, longitude: -86.1163, altitude: 215, speed: 0, heading: 0, satellites: 9, hdop: 1.8, accuracy: 8.2, lastFix: minutesAgo(3), lastLocation: 'Indianapolis, IN' },
    lock: { lockStatus: true, doorStatus: false, motorStatus: 'idle', motorCurrent: 0, positionSensor: true, lastLockTime: hoursAgo(6), lastUnlockTime: hoursAgo(8), unlockMethod: 'bluetooth', unlockCount: 89, failedUnlockCount: 0 },
    access: { keypad: { enabled: true, lastUsed: hoursAgo(6), count: 45 }, nfc: { enabled: false, lastUsed: '', count: 0 }, bluetooth: { enabled: true, lastUsed: hoursAgo(8), count: 38 }, remote: { enabled: true, lastUsed: daysAgo(1), count: 6 } },
    tamper: { tamperStatus: false, caseOpen: false, wireCut: false, lockBreak: false, abnormalVibration: false, forcedUnlock: false, tamperCount: 0, lastTamperTime: '' },
    accelerometer: { motion: false, x: 0.01, y: -0.02, z: 9.79, harshBraking: false, harshAcceleration: false, sharpTurn: false, impactCount: 0, drivingScore: 92 },
    trip: { vehicleStatus: 'stationary', tripStatus: false, tripId: '', distance: 0, maximumSpeed: 0, overspeedCount: 0 },
    geofence: { status: 'inside', geofenceId: 'GF-INDY-001', violation: false, lastEvent: daysAgo(5) },
    sensors: { temperature: 70.1, internalTemperature: 82.4, humidity: 52, hardwareSensorStatus: true },
    security: { deviceBinding: true, vehicleId: 'VH-2024-002', customerId: 'CUST-1002', certificateStatus: true, secureBoot: true, firmwareSignature: true },
    memory: { totalStorage: 16384, usedStorage: 3584, freeStorage: 12800 },
    diagnostics: { lastDiagnosticTime: hoursAgo(1), errorCodes: [], systemHealth: 'good' },
    rtc: { rtcTime: minutesAgo(2), rtcSynced: true },
  },
  {
    deviceId: 'SL-003',
    deviceName: 'Parking Garage Gate',
    status: 'warning',
    lastSeen: minutesAgo(8),
    device: { imei: '352781049265834', modelId: 'SL-PRO-200', serialNumber: 'SN-PG-2024-003', appVersion: '2.4.0', sdkVersion: '1.8.2', hardwareVersion: 'HW3.1', bootReason: 'power_on', uptime: 172800 },
    power: { batteryVoltage: 3.62, batteryPercentage: 23, isCharging: false, isUsbConnected: false, isExternalPower: false, isLowBattery: true },
    cellular: { operator: 'Verizon', networkType: 'LTE-M', rssi: -91, signalQuality: 45, ip: '10.24.36.178' },
    gps: { isFixed: true, latitude: 39.7841, longitude: -86.1495, altitude: 220, speed: 0, heading: 0, satellites: 7, hdop: 2.4, accuracy: 12.1, lastFix: minutesAgo(6), lastLocation: 'Indianapolis, IN' },
    lock: { lockStatus: false, doorStatus: true, motorStatus: 'running', motorCurrent: 1.2, positionSensor: false, lastLockTime: hoursAgo(1), lastUnlockTime: minutesAgo(15), unlockMethod: 'remote', unlockCount: 203, failedUnlockCount: 5 },
    access: { keypad: { enabled: true, lastUsed: minutesAgo(30), count: 120 }, nfc: { enabled: true, lastUsed: hoursAgo(3), count: 45 }, bluetooth: { enabled: true, lastUsed: hoursAgo(2), count: 28 }, remote: { enabled: true, lastUsed: minutesAgo(15), count: 10 } },
    tamper: { tamperStatus: false, caseOpen: false, wireCut: false, lockBreak: false, abnormalVibration: true, forcedUnlock: false, tamperCount: 3, lastTamperTime: daysAgo(2) },
    accelerometer: { motion: false, x: 0.05, y: -0.03, z: 9.78, harshBraking: false, harshAcceleration: false, sharpTurn: false, impactCount: 3, drivingScore: 78 },
    trip: { vehicleStatus: 'stationary', tripStatus: false, tripId: '', distance: 0, maximumSpeed: 0, overspeedCount: 0 },
    geofence: { status: 'inside', geofenceId: 'GF-INDY-001', violation: false, lastEvent: daysAgo(4) },
    sensors: { temperature: 74.8, internalTemperature: 88.1, humidity: 48, hardwareSensorStatus: true },
    security: { deviceBinding: true, vehicleId: 'VH-2024-003', customerId: 'CUST-1003', certificateStatus: true, secureBoot: true, firmwareSignature: true },
    memory: { totalStorage: 16384, usedStorage: 6144, freeStorage: 10240 },
    diagnostics: { lastDiagnosticTime: minutesAgo(15), errorCodes: ['E001', 'E014'], systemHealth: 'warning' },
    rtc: { rtcTime: minutesAgo(4), rtcSynced: true },
  },
  {
    deviceId: 'SL-004',
    deviceName: 'Office Main Entrance',
    status: 'online',
    lastSeen: minutesAgo(1),
    device: { imei: '359174026538921', modelId: 'SL-PRO-200', serialNumber: 'SN-OF-2024-004', appVersion: '2.4.1', sdkVersion: '1.8.3', hardwareVersion: 'HW3.2', bootReason: 'power_on', uptime: 604800 },
    power: { batteryVoltage: 4.08, batteryPercentage: 78, isCharging: true, isUsbConnected: true, isExternalPower: true, isLowBattery: false },
    cellular: { operator: 'T-Mobile', networkType: 'LTE-M', rssi: -68, signalQuality: 92, ip: '10.24.36.88' },
    gps: { isFixed: true, latitude: 39.7712, longitude: -86.1638, altitude: 217, speed: 0, heading: 0, satellites: 14, hdop: 0.9, accuracy: 3.2, lastFix: minutesAgo(1), lastLocation: 'Indianapolis, IN' },
    lock: { lockStatus: true, doorStatus: false, motorStatus: 'idle', motorCurrent: 0, positionSensor: true, lastLockTime: minutesAgo(30), lastUnlockTime: minutesAgo(45), unlockMethod: 'keypad', unlockCount: 312, failedUnlockCount: 1 },
    access: { keypad: { enabled: true, lastUsed: minutesAgo(30), count: 198 }, nfc: { enabled: true, lastUsed: minutesAgo(60), count: 89 }, bluetooth: { enabled: true, lastUsed: hoursAgo(4), count: 15 }, remote: { enabled: true, lastUsed: minutesAgo(45), count: 10 } },
    tamper: { tamperStatus: false, caseOpen: false, wireCut: false, lockBreak: false, abnormalVibration: false, forcedUnlock: false, tamperCount: 0, lastTamperTime: '' },
    accelerometer: { motion: false, x: 0.01, y: -0.01, z: 9.8, harshBraking: false, harshAcceleration: false, sharpTurn: false, impactCount: 0, drivingScore: 98 },
    trip: { vehicleStatus: 'stationary', tripStatus: false, tripId: '', distance: 0, maximumSpeed: 0, overspeedCount: 0 },
    geofence: { status: 'inside', geofenceId: 'GF-INDY-001', violation: false, lastEvent: daysAgo(7) },
    sensors: { temperature: 71.2, internalTemperature: 83.7, humidity: 44, hardwareSensorStatus: true },
    security: { deviceBinding: true, vehicleId: 'VH-2024-004', customerId: 'CUST-1004', certificateStatus: true, secureBoot: true, firmwareSignature: true },
    memory: { totalStorage: 16384, usedStorage: 2816, freeStorage: 13568 },
    diagnostics: { lastDiagnosticTime: minutesAgo(5), errorCodes: [], systemHealth: 'good' },
    rtc: { rtcTime: minutesAgo(1), rtcSynced: true },
  },
  {
    deviceId: 'SL-005',
    deviceName: 'Delivery Loading Dock',
    status: 'offline',
    lastSeen: daysAgo(2),
    device: { imei: '353826017485192', modelId: 'SL-STD-100', serialNumber: 'SN-DL-2024-005', appVersion: '2.3.5', sdkVersion: '1.7.6', hardwareVersion: 'HW2.9', bootReason: 'low_power_sleep', uptime: 0 },
    power: { batteryVoltage: 3.21, batteryPercentage: 5, isCharging: false, isUsbConnected: false, isExternalPower: false, isLowBattery: true },
    cellular: { operator: 'AT&T', networkType: 'LTE-M', rssi: -105, signalQuality: 12, ip: '10.24.36.42' },
    gps: { isFixed: false, latitude: 39.7489, longitude: -86.1352, altitude: 216, speed: 0, heading: 0, satellites: 0, hdop: 99.99, accuracy: 999, lastFix: daysAgo(2), lastLocation: 'Indianapolis, IN' },
    lock: { lockStatus: true, doorStatus: false, motorStatus: 'idle', motorCurrent: 0, positionSensor: true, lastLockTime: daysAgo(2), lastUnlockTime: daysAgo(2), unlockMethod: 'nfc', unlockCount: 67, failedUnlockCount: 3 },
    access: { keypad: { enabled: true, lastUsed: daysAgo(2), count: 30 }, nfc: { enabled: true, lastUsed: daysAgo(2), count: 25 }, bluetooth: { enabled: true, lastUsed: daysAgo(3), count: 8 }, remote: { enabled: true, lastUsed: daysAgo(2), count: 4 } },
    tamper: { tamperStatus: true, caseOpen: false, wireCut: false, lockBreak: false, abnormalVibration: false, forcedUnlock: true, tamperCount: 1, lastTamperTime: daysAgo(2) },
    accelerometer: { motion: false, x: 0, y: 0, z: 0, harshBraking: false, harshAcceleration: false, sharpTurn: false, impactCount: 0, drivingScore: 0 },
    trip: { vehicleStatus: 'stationary', tripStatus: false, tripId: '', distance: 0, maximumSpeed: 0, overspeedCount: 0 },
    geofence: { status: 'outside', geofenceId: 'GF-INDY-001', violation: true, lastEvent: daysAgo(2) },
    sensors: { temperature: 0, internalTemperature: 0, humidity: 0, hardwareSensorStatus: false },
    security: { deviceBinding: true, vehicleId: 'VH-2024-005', customerId: 'CUST-1005', certificateStatus: true, secureBoot: true, firmwareSignature: false },
    memory: { totalStorage: 16384, usedStorage: 8192, freeStorage: 8192 },
    diagnostics: { lastDiagnosticTime: daysAgo(2), errorCodes: ['E002', 'E007', 'E019'], systemHealth: 'critical' },
    rtc: { rtcTime: daysAgo(2), rtcSynced: false },
  },
  {
    deviceId: 'SL-006',
    deviceName: 'Perimeter Gate East',
    status: 'online',
    lastSeen: minutesAgo(3),
    device: { imei: '356247039182645', modelId: 'SL-PRO-200', serialNumber: 'SN-PG-2024-006', appVersion: '2.4.1', sdkVersion: '1.8.3', hardwareVersion: 'HW3.2', bootReason: 'power_on', uptime: 432000 },
    power: { batteryVoltage: 3.96, batteryPercentage: 45, isCharging: false, isUsbConnected: false, isExternalPower: false, isLowBattery: false },
    cellular: { operator: 'Verizon', networkType: 'LTE-M', rssi: -78, signalQuality: 72, ip: '10.24.36.134' },
    gps: { isFixed: true, latitude: 39.7967, longitude: -86.1427, altitude: 222, speed: 15, heading: 90, satellites: 10, hdop: 1.5, accuracy: 5.8, lastFix: minutesAgo(2), lastLocation: 'Indianapolis, IN' },
    lock: { lockStatus: false, doorStatus: true, motorStatus: 'idle', motorCurrent: 0, positionSensor: false, lastLockTime: minutesAgo(20), lastUnlockTime: minutesAgo(10), unlockMethod: 'bluetooth', unlockCount: 178, failedUnlockCount: 4 },
    access: { keypad: { enabled: true, lastUsed: minutesAgo(20), count: 100 }, nfc: { enabled: true, lastUsed: hoursAgo(6), count: 42 }, bluetooth: { enabled: true, lastUsed: minutesAgo(10), count: 26 }, remote: { enabled: true, lastUsed: minutesAgo(10), count: 10 } },
    tamper: { tamperStatus: false, caseOpen: false, wireCut: false, lockBreak: false, abnormalVibration: false, forcedUnlock: false, tamperCount: 0, lastTamperTime: '' },
    accelerometer: { motion: true, x: 0.35, y: -0.12, z: 9.75, harshBraking: false, harshAcceleration: false, sharpTurn: false, impactCount: 0, drivingScore: 88 },
    trip: { vehicleStatus: 'moving', tripStatus: true, tripId: 'TRIP-2024-0089', distance: 3.2, maximumSpeed: 35, overspeedCount: 0 },
    geofence: { status: 'inside', geofenceId: 'GF-INDY-001', violation: false, lastEvent: daysAgo(1) },
    sensors: { temperature: 68.4, internalTemperature: 81.9, humidity: 55, hardwareSensorStatus: true },
    security: { deviceBinding: true, vehicleId: 'VH-2024-006', customerId: 'CUST-1006', certificateStatus: true, secureBoot: true, firmwareSignature: true },
    memory: { totalStorage: 16384, usedStorage: 4608, freeStorage: 11776 },
    diagnostics: { lastDiagnosticTime: minutesAgo(20), errorCodes: [], systemHealth: 'good' },
    rtc: { rtcTime: minutesAgo(1), rtcSynced: true },
  },
  {
    deviceId: 'SL-007',
    deviceName: 'Back Service Door',
    status: 'offline',
    lastSeen: daysAgo(5),
    device: { imei: '351963045218764', modelId: 'SL-STD-100', serialNumber: 'SN-BS-2024-007', appVersion: '2.3.2', sdkVersion: '1.7.4', hardwareVersion: 'HW2.8', bootReason: 'power_on', uptime: 0 },
    power: { batteryVoltage: 3.42, batteryPercentage: 12, isCharging: false, isUsbConnected: false, isExternalPower: false, isLowBattery: true },
    cellular: { operator: 'T-Mobile', networkType: 'LTE-M', rssi: -99, signalQuality: 28, ip: '10.24.36.76' },
    gps: { isFixed: false, latitude: 39.7568, longitude: -86.1724, altitude: 219, speed: 0, heading: 0, satellites: 0, hdop: 99.99, accuracy: 999, lastFix: daysAgo(5), lastLocation: 'Indianapolis, IN' },
    lock: { lockStatus: false, doorStatus: true, motorStatus: 'idle', motorCurrent: 0, positionSensor: false, lastLockTime: daysAgo(5), lastUnlockTime: daysAgo(5), unlockMethod: 'keypad', unlockCount: 34, failedUnlockCount: 7 },
    access: { keypad: { enabled: true, lastUsed: daysAgo(5), count: 20 }, nfc: { enabled: true, lastUsed: daysAgo(6), count: 8 }, bluetooth: { enabled: true, lastUsed: daysAgo(7), count: 4 }, remote: { enabled: true, lastUsed: daysAgo(5), count: 2 } },
    tamper: { tamperStatus: false, caseOpen: true, wireCut: false, lockBreak: false, abnormalVibration: false, forcedUnlock: false, tamperCount: 1, lastTamperTime: daysAgo(5) },
    accelerometer: { motion: false, x: 0, y: 0, z: 0, harshBraking: false, harshAcceleration: false, sharpTurn: false, impactCount: 0, drivingScore: 0 },
    trip: { vehicleStatus: 'stationary', tripStatus: false, tripId: '', distance: 0, maximumSpeed: 0, overspeedCount: 0 },
    geofence: { status: 'inside', geofenceId: 'GF-INDY-001', violation: false, lastEvent: daysAgo(5) },
    sensors: { temperature: 0, internalTemperature: 0, humidity: 0, hardwareSensorStatus: false },
    security: { deviceBinding: true, vehicleId: 'VH-2024-007', customerId: 'CUST-1007', certificateStatus: false, secureBoot: true, firmwareSignature: false },
    memory: { totalStorage: 8192, usedStorage: 5120, freeStorage: 3072 },
    diagnostics: { lastDiagnosticTime: daysAgo(5), errorCodes: ['E003', 'E008', 'E012'], systemHealth: 'critical' },
    rtc: { rtcTime: daysAgo(5), rtcSynced: false },
  },
  {
    deviceId: 'SL-008',
    deviceName: 'Emergency Exit South',
    status: 'online',
    lastSeen: minutesAgo(4),
    device: { imei: '358421056392847', modelId: 'SL-PRO-200', serialNumber: 'SN-EE-2024-008', appVersion: '2.4.1', sdkVersion: '1.8.3', hardwareVersion: 'HW3.2', bootReason: 'power_on', uptime: 259200 },
    power: { batteryVoltage: 4.2, batteryPercentage: 100, isCharging: false, isUsbConnected: false, isExternalPower: true, isLowBattery: false },
    cellular: { operator: 'AT&T', networkType: 'LTE-M', rssi: -74, signalQuality: 80, ip: '10.24.36.199' },
    gps: { isFixed: true, latitude: 39.7398, longitude: -86.1285, altitude: 214, speed: 0, heading: 0, satellites: 11, hdop: 1.1, accuracy: 3.8, lastFix: minutesAgo(3), lastLocation: 'Indianapolis, IN' },
    lock: { lockStatus: true, doorStatus: false, motorStatus: 'idle', motorCurrent: 0, positionSensor: true, lastLockTime: hoursAgo(4), lastUnlockTime: hoursAgo(6), unlockMethod: 'remote', unlockCount: 95, failedUnlockCount: 0 },
    access: { keypad: { enabled: true, lastUsed: hoursAgo(4), count: 55 }, nfc: { enabled: true, lastUsed: hoursAgo(12), count: 22 }, bluetooth: { enabled: true, lastUsed: daysAgo(1), count: 12 }, remote: { enabled: true, lastUsed: hoursAgo(6), count: 6 } },
    tamper: { tamperStatus: false, caseOpen: false, wireCut: false, lockBreak: false, abnormalVibration: false, forcedUnlock: false, tamperCount: 0, lastTamperTime: '' },
    accelerometer: { motion: false, x: 0.03, y: -0.02, z: 9.82, harshBraking: false, harshAcceleration: false, sharpTurn: false, impactCount: 0, drivingScore: 96 },
    trip: { vehicleStatus: 'stationary', tripStatus: false, tripId: '', distance: 0, maximumSpeed: 0, overspeedCount: 0 },
    geofence: { status: 'inside', geofenceId: 'GF-INDY-001', violation: false, lastEvent: daysAgo(6) },
    sensors: { temperature: 73.6, internalTemperature: 86.3, humidity: 42, hardwareSensorStatus: true },
    security: { deviceBinding: true, vehicleId: 'VH-2024-008', customerId: 'CUST-1008', certificateStatus: true, secureBoot: true, firmwareSignature: true },
    memory: { totalStorage: 16384, usedStorage: 3328, freeStorage: 13056 },
    diagnostics: { lastDiagnosticTime: minutesAgo(10), errorCodes: [], systemHealth: 'good' },
    rtc: { rtcTime: minutesAgo(1), rtcSynced: true },
  },
];

export const mockAlerts: Alert[] = [
  { id: 'ALT-001', deviceId: 'SL-005', type: 'low_battery', message: 'Battery critically low at 5%. Device may go offline soon.', severity: 'critical', timestamp: hoursAgo(1), acknowledged: false },
  { id: 'ALT-002', deviceId: 'SL-005', type: 'device_offline', message: 'Device has gone offline. Last seen 2 days ago.', severity: 'critical', timestamp: daysAgo(2), acknowledged: false },
  { id: 'ALT-003', deviceId: 'SL-005', type: 'forced_unlock', message: 'Forced unlock detected at Delivery Loading Dock.', severity: 'critical', timestamp: daysAgo(2), acknowledged: false },
  { id: 'ALT-004', deviceId: 'SL-007', type: 'device_offline', message: 'Device has gone offline. Last seen 5 days ago.', severity: 'critical', timestamp: daysAgo(5), acknowledged: true },
  { id: 'ALT-005', deviceId: 'SL-007', type: 'case_open', message: 'Device case opened at Back Service Door.', severity: 'critical', timestamp: daysAgo(5), acknowledged: true },
  { id: 'ALT-006', deviceId: 'SL-003', type: 'low_battery', message: 'Battery low at 23%. Please charge soon.', severity: 'warning', timestamp: hoursAgo(4), acknowledged: false },
  { id: 'ALT-007', deviceId: 'SL-003', type: 'abnormal_vibration', message: 'Abnormal vibration detected at Parking Garage Gate.', severity: 'warning', timestamp: daysAgo(2), acknowledged: true },
  { id: 'ALT-008', deviceId: 'SL-005', type: 'geofence_violation', message: 'Device has left the designated geofence area.', severity: 'warning', timestamp: daysAgo(2), acknowledged: false },
  { id: 'ALT-009', deviceId: 'SL-003', type: 'failed_unlock', message: '5 failed unlock attempts detected at Parking Garage Gate.', severity: 'warning', timestamp: hoursAgo(6), acknowledged: false },
  { id: 'ALT-010', deviceId: 'SL-001', type: 'unlock_event', message: 'Front Gate Lock unlocked via keypad.', severity: 'info', timestamp: hoursAgo(3), acknowledged: true },
  { id: 'ALT-011', deviceId: 'SL-004', type: 'lock_event', message: 'Office Main Entrance locked via keypad.', severity: 'info', timestamp: minutesAgo(30), acknowledged: true },
  { id: 'ALT-012', deviceId: 'SL-006', type: 'unlock_event', message: 'Perimeter Gate East unlocked via bluetooth.', severity: 'info', timestamp: minutesAgo(10), acknowledged: true },
  { id: 'ALT-013', deviceId: 'SL-008', type: 'lock_event', message: 'Emergency Exit South locked via remote command.', severity: 'info', timestamp: hoursAgo(4), acknowledged: true },
  { id: 'ALT-014', deviceId: 'SL-006', type: 'overspeed', message: 'Vehicle reached maximum speed of 35 km/h.', severity: 'info', timestamp: minutesAgo(8), acknowledged: true },
  { id: 'ALT-015', deviceId: 'SL-002', type: 'unlock_event', message: 'Warehouse Side Door unlocked via bluetooth.', severity: 'info', timestamp: hoursAgo(8), acknowledged: true },
  { id: 'ALT-016', deviceId: 'SL-001', type: 'tamper_detected', message: 'Tamper event logged on Front Gate Lock (historical).', severity: 'warning', timestamp: daysAgo(14), acknowledged: true },
  { id: 'ALT-017', deviceId: 'SL-003', type: 'wire_cut', message: 'Wire cut sensor triggered on Parking Garage Gate.', severity: 'critical', timestamp: daysAgo(10), acknowledged: true },
  { id: 'ALT-018', deviceId: 'SL-007', type: 'lock_break', message: 'Lock break sensor triggered at Back Service Door.', severity: 'critical', timestamp: daysAgo(6), acknowledged: true },
];

export const mockLocationHistory: LocationHistoryEntry[] = [
  { id: 'LH-001', deviceId: 'SL-001', latitude: 39.7684, longitude: -86.1581, altitude: 218, speed: 0, heading: 0, accuracy: 4.5, timestamp: minutesAgo(1), isFixed: true },
  { id: 'LH-002', deviceId: 'SL-001', latitude: 39.7684, longitude: -86.1581, altitude: 218, speed: 0, heading: 0, accuracy: 4.6, timestamp: minutesAgo(60), isFixed: true },
  { id: 'LH-003', deviceId: 'SL-001', latitude: 39.7683, longitude: -86.1582, altitude: 218, speed: 0, heading: 0, accuracy: 4.8, timestamp: hoursAgo(6), isFixed: true },
  { id: 'LH-004', deviceId: 'SL-001', latitude: 39.7684, longitude: -86.1580, altitude: 218, speed: 0, heading: 0, accuracy: 5.0, timestamp: daysAgo(1), isFixed: true },
  { id: 'LH-005', deviceId: 'SL-001', latitude: 39.7685, longitude: -86.1581, altitude: 218, speed: 0, heading: 0, accuracy: 4.3, timestamp: daysAgo(2), isFixed: true },
  { id: 'LH-006', deviceId: 'SL-001', latitude: 39.7684, longitude: -86.1582, altitude: 218, speed: 0, heading: 0, accuracy: 4.7, timestamp: daysAgo(3), isFixed: true },
  { id: 'LH-007', deviceId: 'SL-001', latitude: 39.7684, longitude: -86.1581, altitude: 218, speed: 0, heading: 0, accuracy: 4.4, timestamp: daysAgo(5), isFixed: true },
  { id: 'LH-008', deviceId: 'SL-002', latitude: 39.7321, longitude: -86.1163, altitude: 215, speed: 0, heading: 0, accuracy: 8.2, timestamp: minutesAgo(3), isFixed: true },
  { id: 'LH-009', deviceId: 'SL-002', latitude: 39.7321, longitude: -86.1163, altitude: 215, speed: 0, heading: 0, accuracy: 8.5, timestamp: hoursAgo(4), isFixed: true },
  { id: 'LH-010', deviceId: 'SL-002', latitude: 39.7322, longitude: -86.1164, altitude: 215, speed: 0, heading: 0, accuracy: 9.1, timestamp: daysAgo(1), isFixed: true },
  { id: 'LH-011', deviceId: 'SL-002', latitude: 39.7321, longitude: -86.1163, altitude: 215, speed: 0, heading: 0, accuracy: 8.8, timestamp: daysAgo(3), isFixed: true },
  { id: 'LH-012', deviceId: 'SL-002', latitude: 39.7320, longitude: -86.1162, altitude: 215, speed: 0, heading: 0, accuracy: 8.0, timestamp: daysAgo(5), isFixed: true },
  { id: 'LH-013', deviceId: 'SL-003', latitude: 39.7841, longitude: -86.1495, altitude: 220, speed: 0, heading: 0, accuracy: 12.1, timestamp: minutesAgo(6), isFixed: true },
  { id: 'LH-014', deviceId: 'SL-003', latitude: 39.7840, longitude: -86.1494, altitude: 220, speed: 0, heading: 0, accuracy: 11.8, timestamp: hoursAgo(3), isFixed: true },
  { id: 'LH-015', deviceId: 'SL-003', latitude: 39.7842, longitude: -86.1496, altitude: 220, speed: 0, heading: 0, accuracy: 12.5, timestamp: daysAgo(1), isFixed: true },
  { id: 'LH-016', deviceId: 'SL-003', latitude: 39.7841, longitude: -86.1495, altitude: 220, speed: 0, heading: 0, accuracy: 13.0, timestamp: daysAgo(3), isFixed: true },
  { id: 'LH-017', deviceId: 'SL-003', latitude: 39.7840, longitude: -86.1495, altitude: 220, speed: 0, heading: 0, accuracy: 12.2, timestamp: daysAgo(5), isFixed: true },
  { id: 'LH-018', deviceId: 'SL-004', latitude: 39.7712, longitude: -86.1638, altitude: 217, speed: 0, heading: 0, accuracy: 3.2, timestamp: minutesAgo(1), isFixed: true },
  { id: 'LH-019', deviceId: 'SL-004', latitude: 39.7712, longitude: -86.1638, altitude: 217, speed: 0, heading: 0, accuracy: 3.4, timestamp: minutesAgo(30), isFixed: true },
  { id: 'LH-020', deviceId: 'SL-004', latitude: 39.7711, longitude: -86.1637, altitude: 217, speed: 0, heading: 0, accuracy: 3.6, timestamp: hoursAgo(6), isFixed: true },
  { id: 'LH-021', deviceId: 'SL-004', latitude: 39.7712, longitude: -86.1638, altitude: 217, speed: 0, heading: 0, accuracy: 3.1, timestamp: daysAgo(1), isFixed: true },
  { id: 'LH-022', deviceId: 'SL-004', latitude: 39.7713, longitude: -86.1639, altitude: 217, speed: 0, heading: 0, accuracy: 3.5, timestamp: daysAgo(3), isFixed: true },
  { id: 'LH-023', deviceId: 'SL-004', latitude: 39.7712, longitude: -86.1638, altitude: 217, speed: 0, heading: 0, accuracy: 3.3, timestamp: daysAgo(5), isFixed: true },
  { id: 'LH-024', deviceId: 'SL-004', latitude: 39.7712, longitude: -86.1638, altitude: 217, speed: 0, heading: 0, accuracy: 3.0, timestamp: daysAgo(7), isFixed: true },
  { id: 'LH-025', deviceId: 'SL-006', latitude: 39.7967, longitude: -86.1427, altitude: 222, speed: 15, heading: 90, accuracy: 5.8, timestamp: minutesAgo(2), isFixed: true },
  { id: 'LH-026', deviceId: 'SL-006', latitude: 39.7962, longitude: -86.1418, altitude: 222, speed: 22, heading: 85, accuracy: 6.1, timestamp: minutesAgo(5), isFixed: true },
  { id: 'LH-027', deviceId: 'SL-006', latitude: 39.7958, longitude: -86.1409, altitude: 222, speed: 28, heading: 80, accuracy: 5.5, timestamp: minutesAgo(8), isFixed: true },
  { id: 'LH-028', deviceId: 'SL-006', latitude: 39.7951, longitude: -86.1398, altitude: 222, speed: 30, heading: 75, accuracy: 5.2, timestamp: minutesAgo(11), isFixed: true },
  { id: 'LH-029', deviceId: 'SL-006', latitude: 39.7965, longitude: -86.1425, altitude: 222, speed: 0, heading: 0, accuracy: 6.0, timestamp: hoursAgo(2), isFixed: true },
  { id: 'LH-030', deviceId: 'SL-006', latitude: 39.7967, longitude: -86.1427, altitude: 222, speed: 0, heading: 0, accuracy: 5.9, timestamp: hoursAgo(6), isFixed: true },
  { id: 'LH-031', deviceId: 'SL-006', latitude: 39.7966, longitude: -86.1426, altitude: 222, speed: 0, heading: 0, accuracy: 5.7, timestamp: daysAgo(1), isFixed: true },
  { id: 'LH-032', deviceId: 'SL-008', latitude: 39.7398, longitude: -86.1285, altitude: 214, speed: 0, heading: 0, accuracy: 3.8, timestamp: minutesAgo(3), isFixed: true },
  { id: 'LH-033', deviceId: 'SL-008', latitude: 39.7398, longitude: -86.1285, altitude: 214, speed: 0, heading: 0, accuracy: 4.0, timestamp: hoursAgo(3), isFixed: true },
  { id: 'LH-034', deviceId: 'SL-008', latitude: 39.7397, longitude: -86.1284, altitude: 214, speed: 0, heading: 0, accuracy: 3.9, timestamp: hoursAgo(8), isFixed: true },
  { id: 'LH-035', deviceId: 'SL-008', latitude: 39.7398, longitude: -86.1286, altitude: 214, speed: 0, heading: 0, accuracy: 4.1, timestamp: daysAgo(1), isFixed: true },
  { id: 'LH-036', deviceId: 'SL-008', latitude: 39.7399, longitude: -86.1285, altitude: 214, speed: 0, heading: 0, accuracy: 3.7, timestamp: daysAgo(2), isFixed: true },
  { id: 'LH-037', deviceId: 'SL-008', latitude: 39.7398, longitude: -86.1285, altitude: 214, speed: 0, heading: 0, accuracy: 3.6, timestamp: daysAgo(4), isFixed: true },
  { id: 'LH-038', deviceId: 'SL-008', latitude: 39.7397, longitude: -86.1284, altitude: 214, speed: 0, heading: 0, accuracy: 4.2, timestamp: daysAgo(6), isFixed: true },
  { id: 'LH-039', deviceId: 'SL-005', latitude: 39.7489, longitude: -86.1352, altitude: 216, speed: 0, heading: 0, accuracy: 999, timestamp: daysAgo(2), isFixed: false },
  { id: 'LH-040', deviceId: 'SL-005', latitude: 39.7488, longitude: -86.1351, altitude: 216, speed: 0, heading: 0, accuracy: 9.5, timestamp: daysAgo(2), isFixed: true },
  { id: 'LH-041', deviceId: 'SL-005', latitude: 39.7489, longitude: -86.1352, altitude: 216, speed: 0, heading: 0, accuracy: 9.8, timestamp: daysAgo(3), isFixed: true },
  { id: 'LH-042', deviceId: 'SL-007', latitude: 39.7568, longitude: -86.1724, altitude: 219, speed: 0, heading: 0, accuracy: 999, timestamp: daysAgo(5), isFixed: false },
  { id: 'LH-043', deviceId: 'SL-007', latitude: 39.7567, longitude: -86.1723, altitude: 219, speed: 0, heading: 0, accuracy: 10.2, timestamp: daysAgo(5), isFixed: true },
  { id: 'LH-044', deviceId: 'SL-001', latitude: 39.7684, longitude: -86.1581, altitude: 218, speed: 0, heading: 0, accuracy: 4.9, timestamp: daysAgo(4), isFixed: true },
  { id: 'LH-045', deviceId: 'SL-003', latitude: 39.7841, longitude: -86.1495, altitude: 220, speed: 0, heading: 0, accuracy: 11.9, timestamp: daysAgo(4), isFixed: true },
  { id: 'LH-046', deviceId: 'SL-006', latitude: 39.7967, longitude: -86.1427, altitude: 222, speed: 0, heading: 0, accuracy: 6.2, timestamp: daysAgo(2), isFixed: true },
  { id: 'LH-047', deviceId: 'SL-004', latitude: 39.7712, longitude: -86.1638, altitude: 217, speed: 0, heading: 0, accuracy: 3.4, timestamp: daysAgo(4), isFixed: true },
  { id: 'LH-048', deviceId: 'SL-008', latitude: 39.7398, longitude: -86.1285, altitude: 214, speed: 0, heading: 0, accuracy: 3.9, timestamp: daysAgo(3), isFixed: true },
  { id: 'LH-049', deviceId: 'SL-002', latitude: 39.7321, longitude: -86.1163, altitude: 215, speed: 0, heading: 0, accuracy: 8.3, timestamp: daysAgo(4), isFixed: true },
  { id: 'LH-050', deviceId: 'SL-001', latitude: 39.7684, longitude: -86.1581, altitude: 218, speed: 0, heading: 0, accuracy: 4.6, timestamp: daysAgo(6), isFixed: true },
];

export const mockActivityEvents: ActivityEvent[] = [
  { id: 'AE-001', deviceId: 'SL-001', type: 'lock', message: 'Front Gate Lock locked via keypad', timestamp: hoursAgo(2), metadata: { method: 'keypad' } },
  { id: 'AE-002', deviceId: 'SL-001', type: 'unlock', message: 'Front Gate Lock unlocked via keypad', timestamp: hoursAgo(3), metadata: { method: 'keypad' } },
  { id: 'AE-003', deviceId: 'SL-004', type: 'lock', message: 'Office Main Entrance locked via keypad', timestamp: minutesAgo(30), metadata: { method: 'keypad' } },
  { id: 'AE-004', deviceId: 'SL-004', type: 'unlock', message: 'Office Main Entrance unlocked via keypad', timestamp: minutesAgo(45), metadata: { method: 'keypad' } },
  { id: 'AE-005', deviceId: 'SL-006', type: 'unlock', message: 'Perimeter Gate East unlocked via bluetooth', timestamp: minutesAgo(10), metadata: { method: 'bluetooth' } },
  { id: 'AE-006', deviceId: 'SL-006', type: 'lock', message: 'Perimeter Gate East locked via keypad', timestamp: minutesAgo(20), metadata: { method: 'keypad' } },
  { id: 'AE-007', deviceId: 'SL-008', type: 'lock', message: 'Emergency Exit South locked via remote command', timestamp: hoursAgo(4), metadata: { method: 'remote' } },
  { id: 'AE-008', deviceId: 'SL-008', type: 'unlock', message: 'Emergency Exit South unlocked via remote command', timestamp: hoursAgo(6), metadata: { method: 'remote' } },
  { id: 'AE-009', deviceId: 'SL-002', type: 'unlock', message: 'Warehouse Side Door unlocked via bluetooth', timestamp: hoursAgo(8), metadata: { method: 'bluetooth' } },
  { id: 'AE-010', deviceId: 'SL-002', type: 'lock', message: 'Warehouse Side Door locked via keypad', timestamp: hoursAgo(6), metadata: { method: 'keypad' } },
  { id: 'AE-011', deviceId: 'SL-003', type: 'unlock', message: 'Parking Garage Gate unlocked via remote', timestamp: minutesAgo(15), metadata: { method: 'remote' } },
  { id: 'AE-012', deviceId: 'SL-003', type: 'lock', message: 'Parking Garage Gate locked via keypad', timestamp: hoursAgo(1), metadata: { method: 'keypad' } },
  { id: 'AE-013', deviceId: 'SL-005', type: 'tamper', message: 'Forced unlock attempt at Delivery Loading Dock', timestamp: daysAgo(2), metadata: { tamperType: 'forced_unlock' } },
  { id: 'AE-014', deviceId: 'SL-005', type: 'access', message: 'Last successful access via NFC before offline', timestamp: daysAgo(2), metadata: { method: 'nfc' } },
  { id: 'AE-015', deviceId: 'SL-007', type: 'tamper', message: 'Case opened at Back Service Door', timestamp: daysAgo(5), metadata: { tamperType: 'case_open' } },
  { id: 'AE-016', deviceId: 'SL-001', type: 'location', message: 'Location updated: Indianapolis, IN', timestamp: minutesAgo(1), metadata: { latitude: 39.7684, longitude: -86.1581 } },
  { id: 'AE-017', deviceId: 'SL-004', type: 'location', message: 'Location updated: Indianapolis, IN', timestamp: minutesAgo(1), metadata: { latitude: 39.7712, longitude: -86.1638 } },
  { id: 'AE-018', deviceId: 'SL-006', type: 'location', message: 'Location updated: moving east', timestamp: minutesAgo(2), metadata: { latitude: 39.7967, longitude: -86.1427, speed: 15 } },
  { id: 'AE-019', deviceId: 'SL-006', type: 'remote', message: 'Remote command sent to Perimeter Gate East', timestamp: minutesAgo(10), metadata: { command: 'unlock' } },
  { id: 'AE-020', deviceId: 'SL-008', type: 'remote', message: 'Remote command sent to Emergency Exit South', timestamp: hoursAgo(4), metadata: { command: 'lock' } },
  { id: 'AE-021', deviceId: 'SL-003', type: 'access', message: 'Keypad access at Parking Garage Gate', timestamp: minutesAgo(30), metadata: { method: 'keypad', success: true } },
  { id: 'AE-022', deviceId: 'SL-003', type: 'access', message: 'Failed keypad attempt at Parking Garage Gate', timestamp: hoursAgo(5), metadata: { method: 'keypad', success: false } },
  { id: 'AE-023', deviceId: 'SL-001', type: 'access', message: 'NFC access at Front Gate Lock', timestamp: hoursAgo(5), metadata: { method: 'nfc', success: true } },
  { id: 'AE-024', deviceId: 'SL-004', type: 'access', message: 'NFC access at Office Main Entrance', timestamp: minutesAgo(60), metadata: { method: 'nfc', success: true } },
  { id: 'AE-025', deviceId: 'SL-006', type: 'trip', message: 'Trip started: TRIP-2024-0089', timestamp: minutesAgo(12), metadata: { tripId: 'TRIP-2024-0089' } },
  { id: 'AE-026', deviceId: 'SL-006', type: 'overspeed', message: 'Overspeed event recorded: 35 km/h', timestamp: minutesAgo(8), metadata: { speed: 35, limit: 30 } },
  { id: 'AE-027', deviceId: 'SL-005', type: 'device', message: 'Device went offline', timestamp: daysAgo(2), metadata: { reason: 'low_battery' } },
  { id: 'AE-028', deviceId: 'SL-007', type: 'device', message: 'Device went offline', timestamp: daysAgo(5), metadata: { reason: 'power_off' } },
  { id: 'AE-029', deviceId: 'SL-001', type: 'lock', message: 'Front Gate Lock auto-locked after timeout', timestamp: hoursAgo(4), metadata: { reason: 'auto_lock' } },
  { id: 'AE-030', deviceId: 'SL-004', type: 'unlock', message: 'Office Main Entrance unlocked via remote', timestamp: minutesAgo(45), metadata: { method: 'remote' } },
];
